packages:
  - 'packages/*'
  - docs
  - 'examples/*/*'
allowBuilds:
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
catalog:
  '@cloudflare/workers-types': ^5.20260717.1
  '@total-typescript/tsconfig': ^1.0.4
  typescript: ^7.0.2
  zod: ^4.4.3
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - 'orphos'
  - 'sst'
registries:
  "@jsr": https://npm.jsr.io/
  default: https://registry.npmjs.org/
